# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
inhibit_all_warnings!

target 'WeatherForecast' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    pod 'HydraAsync'
    pod 'Result'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
              config.build_settings['ENABLE_BITCODE'] = 'YES'
            end

            if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
              target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
              end
            end
        end
    end
end
